version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - consumer1
      - consumer2
      - unifying
      - producer1
      - producer2
    networks:
      - lab2network

  producer1:
    build:
      context: producer1
      no_cache: true
    env_file:
      - MSize.env
    networks:
      - lab2network

  producer2:
    build:
      context: producer2
      no_cache: true
    env_file:
      - MSize.env
    networks:
      - lab2network
  consumer1:
    build:
      context: consumer
      no_cache: true
    networks:
      - lab2network
    deploy:
      resources:
        limits:
          cpus: "4"

  consumer2:
    build:
      context: consumer
      no_cache: true
    networks:
      - lab2network
    deploy:
      resources:
        limits:
          cpus: "4"

  unifying:
    build:
      context: unifying
      no_cache: true
    networks:
      - lab2network

networks:
  lab2network:
